/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as ChatsRouteImport } from './routes/chats'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as IntroductionsRouteImport } from './routes/introductions'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ApiExplainMatchRouteImport } from './routes/api/explain-match'
import { Route as ApiParseCustomMatchRouteImport } from './routes/api/parse-custom-match'
import { Route as ChatMatchIdRouteImport } from './routes/chat.$matchId'
import { Route as IntroductionIdRouteImport } from './routes/introduction.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatsRoute = ChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const IntroductionsRoute = IntroductionsRouteImport.update({
  id: '/introductions',
  path: '/introductions',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExplainMatchRoute = ApiExplainMatchRouteImport.update({
  id: '/api/explain-match',
  path: '/api/explain-match',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiParseCustomMatchRoute = ApiParseCustomMatchRouteImport.update({
  id: '/api/parse-custom-match',
  path: '/api/parse-custom-match',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatMatchIdRoute = ChatMatchIdRouteImport.update({
  id: '/chat/$matchId',
  path: '/chat/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)
const IntroductionIdRoute = IntroductionIdRouteImport.update({
  id: '/introduction/$id',
  path: '/introduction/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/chats': typeof ChatsRoute
  '/discover': typeof DiscoverRoute
  '/introductions': typeof IntroductionsRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/api/explain-match': typeof ApiExplainMatchRoute
  '/api/parse-custom-match': typeof ApiParseCustomMatchRoute
  '/chat/$matchId': typeof ChatMatchIdRoute
  '/introduction/$id': typeof IntroductionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/chats': typeof ChatsRoute
  '/discover': typeof DiscoverRoute
  '/introductions': typeof IntroductionsRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/api/explain-match': typeof ApiExplainMatchRoute
  '/api/parse-custom-match': typeof ApiParseCustomMatchRoute
  '/chat/$matchId': typeof ChatMatchIdRoute
  '/introduction/$id': typeof IntroductionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/chats': typeof ChatsRoute
  '/discover': typeof DiscoverRoute
  '/introductions': typeof IntroductionsRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/api/explain-match': typeof ApiExplainMatchRoute
  '/api/parse-custom-match': typeof ApiParseCustomMatchRoute
  '/chat/$matchId': typeof ChatMatchIdRoute
  '/introduction/$id': typeof IntroductionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/chats'
    | '/discover'
    | '/introductions'
    | '/onboarding'
    | '/profile'
    | '/api/explain-match'
    | '/api/parse-custom-match'
    | '/chat/$matchId'
    | '/introduction/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/chats'
    | '/discover'
    | '/introductions'
    | '/onboarding'
    | '/profile'
    | '/api/explain-match'
    | '/api/parse-custom-match'
    | '/chat/$matchId'
    | '/introduction/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/chats'
    | '/discover'
    | '/introductions'
    | '/onboarding'
    | '/profile'
    | '/api/explain-match'
    | '/api/parse-custom-match'
    | '/chat/$matchId'
    | '/introduction/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  ChatsRoute: typeof ChatsRoute
  DiscoverRoute: typeof DiscoverRoute
  IntroductionsRoute: typeof IntroductionsRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfileRoute: typeof ProfileRoute
  ApiExplainMatchRoute: typeof ApiExplainMatchRoute
  ApiParseCustomMatchRoute: typeof ApiParseCustomMatchRoute
  ChatMatchIdRoute: typeof ChatMatchIdRoute
  IntroductionIdRoute: typeof IntroductionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats': {
      id: '/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof ChatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/introductions': {
      id: '/introductions'
      path: '/introductions'
      fullPath: '/introductions'
      preLoaderRoute: typeof IntroductionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/explain-match': {
      id: '/api/explain-match'
      path: '/api/explain-match'
      fullPath: '/api/explain-match'
      preLoaderRoute: typeof ApiExplainMatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/parse-custom-match': {
      id: '/api/parse-custom-match'
      path: '/api/parse-custom-match'
      fullPath: '/api/parse-custom-match'
      preLoaderRoute: typeof ApiParseCustomMatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$matchId': {
      id: '/chat/$matchId'
      path: '/chat/$matchId'
      fullPath: '/chat/$matchId'
      preLoaderRoute: typeof ChatMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/introduction/$id': {
      id: '/introduction/$id'
      path: '/introduction/$id'
      fullPath: '/introduction/$id'
      preLoaderRoute: typeof IntroductionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  ChatsRoute: ChatsRoute,
  DiscoverRoute: DiscoverRoute,
  IntroductionsRoute: IntroductionsRoute,
  OnboardingRoute: OnboardingRoute,
  ProfileRoute: ProfileRoute,
  ApiExplainMatchRoute: ApiExplainMatchRoute,
  ApiParseCustomMatchRoute: ApiParseCustomMatchRoute,
  ChatMatchIdRoute: ChatMatchIdRoute,
  IntroductionIdRoute: IntroductionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
